using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YadLeyadBack.Migrations
{
    /// <inheritdoc />
    public partial class updateStreestAntNeighborhoodsv2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
truncate table Streets;
truncate table Neighborhoods;
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'סנש',383,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אבא נעמת',179,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אהרונסון',370,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אביטל',280,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אביי',340,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אבן גבירול',293,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אדם יקותיאל',237,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'יונתן',376,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אהבת ישראל',215,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אהבת שלום',503,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אוהל יהושע',455,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אולפן המשטרה',150,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אור החיים',222,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אור שמח',224,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אורטל',281,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אזור התעשיה צפון',6500,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אזור תעשיה מערבי',6511,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אחיה השילוני',425,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אחיעזר',223,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אהרן שמי',371,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'האחים',379,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אלון יגאל',148,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אליהו הנביא',473,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אליכין',127,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אלישע הנביא',474,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אלנקוה רפאל',161,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אלעזרי',129,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אמרי אמת',211,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אמרי נועם',504,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אסתר',513,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ארלוזורוב',110,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אשכול לוי',242,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אשר',231,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'באר שבע',487,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בוסקילה יוסף',128,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ביאליק',123,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ביחר שמשון',109,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בית ג''מאל',130,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בית זולוטוב',149,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בית ישראל',226,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בית שמש',9000,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בית שמש הותיקה',6509,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בן איש חי',189,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בן אליעזר',202,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בן גוריון פולה',254,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בן גרא',158,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בן זאב יהודה',252,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בן עזאי',450,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בן צבי',145,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בן ציון אבא שאול',187,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בנאי יוסי',297,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בני דן',124,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בעל התניא',505,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בר אילן',203,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בר קפרא',361,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ברכת אברהם',229,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'גבעת בן צבי',6527,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'גבעת ויצמן',6526,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'גבעת סביון',6517,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'גבעת שזר',6528,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'גבעת שרת',6501,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'גד',232,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'גונן שמואל',240,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'גור אריה',122,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'גלעד',243,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'גני יהודית',6507,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'גני שמש',6502,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'דובר שלום',453,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'דורי יעקב',257,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'דליה',116,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'דם המכבים',111,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'דניאל',515,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'דרך החיים',285,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'דרך רבין יצחק',247,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'דרכי אליעזר',449,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'האגס',272,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'האדמור מבעלזא',502,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'האדמור מרוז''ין',506,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'האדרת',507,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'האומן',106,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'האורן',268,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'האיריס',166,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'האלה',125,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'האפרסק',273,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'האצל',138,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הארבל',244,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הארז',274,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הארזים',174,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'האתרוג',269,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הבנאי',141,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הבעל שם טוב',508,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הברוש',266,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הגאון מוילנא',509,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הגולן',251,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הגליל',248,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הגפן',115,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הדובדבן',176,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הדולב',278,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ההדס',270,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ההדר',263,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ההכשרה',305,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הושע הנביא',476,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הותיקים',155,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'החבצלת',193,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'החוזה מלובלין',526,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'החלוצים',104,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'החפץ חיים',188,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'החצב',191,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'החרובים',264,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'החרוצים',306,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'החרמון',245,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'החרצית',192,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'החרש',152,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'היסמין',195,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'היצירה',301,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הכלנית',167,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הלל',495,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'המגיד ממעזריטש',527,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'המהריל דיסקין',220,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'המורה יעקב',136,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'המכתש',126,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'המלאכה',304,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'המלך דוד',511,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'המסגר',142,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'המעפילים',121,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'המשלט',112,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הנורית',165,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הנציב',528,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הנרקיס',169,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הנשיא',113,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הסביון',168,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הסוללה',308,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הסיגלית',163,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רועי קליין',373,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'העליה',105,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'העמל',303,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הערבה',265,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הערמון',275,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הצאלה',276,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הצבע',310,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הצדיק משטפנשט',448,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הציפורן',194,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הר בשן',286,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הר גבנונים',289,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הר הכרמל',300,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הר המוריה',287,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הר מירון',288,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הר נבו',284,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב אלישיב',534,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב גריינימן',532,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב האדמור החלוץ',531,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב הרצוג',216,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב יוסף עזרן',533,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב יעקב יוסף',535,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב יצחק כדורי',536,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב מבריסק',213,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב מנחם פרוש',537,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב מרדכי צמח אליהו',538,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב קוק',539,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב שלמה זלמן',546,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב שלמה לורניץ',540,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרטוב',279,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרצל',101,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרקפת',164,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרשר הירש',547,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'השבעה',144,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'השושן',190,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'השיזף',277,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'השיטה',261,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'השקד',131,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'התאנה',262,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'התבור',246,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'התעשיה',302,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'התפוח',271,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'וירג''יניה',307,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ורד',207,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ז''בוטינסקי',103,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'זכרון יעקב',209,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'זכריה הנביא',480,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'חבקוק הנביא',481,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'חברון',485,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'חגי הנביא',426,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'חזון איש',212,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'חידא',186,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'חלקת יהושע',541,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'חצרות ערבי הנחל',444,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אלבז',380,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'טבריה',488,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'יאיר',378,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'יבנה',489,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ידין יגאל',255,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'יהודה הלוי',294,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'יהודה המכבי',180,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'יואל הנביא',484,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'יוכבד',542,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'יונה בן אמיתי',427,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'יונתן בן עוזיאל',183,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'יחזקאל הנביא',523,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'יצחק שדה',204,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ירושלים',490,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ירמיהו הנביא',524,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ישעיהו הנביא',521,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'כביש 38',185,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ככר נוימן',6001,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'השלושה',377,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'לב שמחה',221,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'לוין אריה',239,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'לנר דן',235,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'לסקוב חיים',241,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מגן קלמן',236,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מורדי הגטאות',153,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מורי יעקב',157,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מחזיקי הדת',501,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מיטל',282,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מלאכי הנביא',518,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מנדלר אלברט',238,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מנוח',118,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מנור אהוד',296,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מנחת יצחק',228,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מעלה דוד',132,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מעלה הסיירים',133,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מעלה הצופים',134,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מעלה יאיר',135,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מעלות הרמא',500,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מעפילי אגוז',230,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מערבא',354,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מעשי חייא',225,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מצדה',139,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מצפה הרשפ',494,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מקלף מרדכי',256,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מר עוקבא',350,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מרים הנביאה',522,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מרכז קליטה',151,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'משה רבנו',520,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'משטרת הרטוב',108,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'משעול המתמיד',259,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נהר הירדן',410,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נהר הירקון',420,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נהרדעא',351,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נוה ספיר',6519,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נועם אלימלך',544,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נופי אביב',6523,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נופי הדר',178,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחום הנביא',428,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל אוריה',411,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל איילון',412,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל אכזיב',441,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל אל-על',409,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל אלכסנדר',408,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל גילה',413,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל דולב',400,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל הבשור',439,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל הקישון',419,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל זוהר',433,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל זויתן',430,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל חבר',434,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל יעלה',401,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל לוז',414,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל לכיש',415,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל מאור',402,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל מטע',403,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל מיכה',416,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל משמר',442,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל נועם',418,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל נחשון',417,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל ניצנים',443,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל סנסן',445,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל עין גדי',435,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל ערוגות',436,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל קטלב',404,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל רביבים',440,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל רזיאל',405,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל רמות',421,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל רפאים',438,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל שורק',422,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל שחם',423,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל שמשון',406,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל שניר',429,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל תמנע',407,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל תמר',424,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחמיה',516,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'חגואל',384,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נעמי שמר',295,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נפתלי',253,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נריה הנביא',447,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נתיב מאיר',196,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'סולם יעקב',210,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'סורא',360,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'סחלב',208,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'טרומפלדור',372,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'סיני',137,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'סיתוונית',206,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'סמ בן אליעזר',199,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'סמ האלון',181,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'סמ הגפן',154,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'סמ ויצו',143,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'סמ עלית הנוער',249,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'סמדר',117,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'פרנקל',375,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'עזרא',517,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'עידו הנביא',519,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'עלית הנוער',250,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'עמק הזיתים',114,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'עקביא בן מהללאל',452,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'פומפדיתא',355,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'פסגות השבע',6522,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'פעמי משיח',497,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'פרס ראובן',177,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'צפת',491,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'צריפים אדומים',6504,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'קארו יוסף',197,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'קדושת אהרון',457,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'קהילת יעקב',218,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'קריית ארבע',486,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'קרית אריה',6518,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'קרית בן אליעזר',6521,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'קרית החינוך',6532,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'קרית הרב ניסים',6520,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'קרית הרמא',6530,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'קרן היסוד',147,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ראובן',234,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב אבדימי',357,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב אבהו',332,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב אמי',338,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב אמימר',342,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב אשי',339,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב המנונא',349,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב זביד',337,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב זירא',343,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב חנן',345,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב כהנא',353,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב מנשיא',348,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב מרי',359,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב עולא',341,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב עמרם',358,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב פפא',336,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב שילא',346,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב ששת',331,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב תנחומא',335,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבא',344,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי אלעזר',465,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי טרפון',468,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי יהודה הנשיא',463,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי יהושע',462,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי יוסי בן קיסמא',451,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי ינאי',458,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי ישמעאל',456,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי לויטס',464,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי מאיר בעל הנס',467,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי עקיבא',460,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי פנחס בן יאיר',454,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי צדוק',469,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי צדקה יהודה',198,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבינא',334,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רביצקי',159,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבן יוחנן בן זכאי',471,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבנו חיים הלוי',217,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רויטל',283,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רות',514,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רזיאל דוד',258,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רחל המשוררת',298,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ריבל',470,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רימון',182,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ריש לקיש',347,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רמבם',140,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רמת בית שמש',6525,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רמת בית שמש ב',6531,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רמת לחי',120,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רשי',205,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רשבג',461,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רשבי',466,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ש 160',6513,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ש 144',6514,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ש 116',6515,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ש ותיקים',6505,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ש חצרות',6506,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ש משק עזר',6508,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ש קוטג''',6512,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ש רמת לחי',6510,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שאול המלך',512,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'משה ארנס',381,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב ספקטור',214,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שביל האשל',171,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שביל הגיחון',437,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שביל הלה',102,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שביל הנחש',446,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שביל התמרים',156,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שד בן גוריון',200,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שד הדקל',162,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שד נהר הדן',201,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שד נחל צאלים',492,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שד'' האמוראים',333,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שועלי שמשון',119,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שכ הגפן',6503,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שכ השחר',6529,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שכ מחסיה',6524,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שכ קרית חזון עובדיה',6534,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שכ רמת התנאים',6533,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שלמה המלך',510,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שמואל הנביא',493,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שמעון',233,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שער השמיים',227,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שפת אמת',219,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שקמה',172,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'תאשור',267,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'תדהר',175,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'תחנת הרכבת',107,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'תכלת מרדכי',459,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'תלמוד בבלי',352,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'תלמוד ירושלמי',356,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'פרנק',374,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'תמר',545,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'תפארת משה',160,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'חביבה רייך',382,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אודם',318,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'אילפא',570,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בזלת',319,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בנימין',323,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'בעל הסולם',325,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'גרניט',316,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'דבורה הנביאה',550,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'דלומיט',315,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'דרכי איש',552,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'המורה צבי',260,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הנביא עובדיה',311,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הנביא עמוס',312,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הנביא צפניה',529,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב אברהם שפירא',551,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב איידלשטיין',553,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב ברוק',556,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב ישראל גרוסמן',554,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'הרב ליפקוביץ',555,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'זעירי',568,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'חולדה הנביאה',314,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'חושן',309,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'טופז',321,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'טורקיז',299,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'יהלום',317,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מר זוטרא',560,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'מר ינוקא',564,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל פולג',530,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל פרת',548,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נחל קדרון',543,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'נתן הנביא',313,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'סלע',322,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'ספיר',320,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'קריסטל',324,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב חלקיה בר טובי',563,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב חננאל',565,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב חסדא',561,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב ייבא סבא',569,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רב משרשיא',567,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי ברכיה',557,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי חזקיה',562,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי חלבו',571,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי חנינא',558,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי יצחק נפחא',559,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'רבי פרדא',566,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'שד נחל נובע',549,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES (N'תפארת נפתלי',525,2610);

INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'א.ת ברוש,בית שמש מערב',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'א.ת הר-טוב',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'א.ת צפוני',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'א.ת שורק-נוחם',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'א.ת שורק-נוחם',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'גבעת משקפיים',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'גבעת שרת',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'הקריה החרדית',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'חזון עובדיה,רמת בית שמש ג--2',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'ממזרח שמש',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'נווה שמיר ,רמת בית שמש ה-1',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'פסגות השבע',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'קנה בושם,חפציבה',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'קרית אריה,שיינפלד',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'רמת אבי עזרי,רמת בית שמש ג-1',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'רמת אברהם',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'רמת בית שמש ה-2',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'רמת האמוראים,רמת בית שמש ד-1',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'רמת האמוראים,רמת בית שמש ד-2',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'רמת האמוראים,רמת בית שמש ד-3',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'רמת האמוראים,רמת בית שמש ד-4',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'רמת האמוראים,רמת בית שמש ד-5',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'רמת הנחלים,רמת בית שמש א',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'רמת התנאים,רמת בית שמש ב',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'רמת משה,בית שמש הוותיקה',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'שכונת המע""ר',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES (N'שכונת מ-3',2610);
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
