using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YadLeyadBack.Migrations
{
    /// <inheritdoc />
    public partial class updateStreestAntNeighborhoods : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                           INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('סנש',383,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אבא נעמת',179,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אהרונסון',370,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אביטל',280,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אביי',340,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אבן גבירול',293,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אדם יקותיאל',237,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('יונתן',376,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אהבת ישראל',215,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אהבת שלום',503,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אוהל יהושע',455,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אולפן המשטרה',150,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אור החיים',222,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אור שמח',224,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אורטל',281,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אזור התעשיה צפון',6500,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אזור תעשיה מערבי',6511,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אחיה השילוני',425,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אחיעזר',223,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אהרן שמי',371,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('האחים',379,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אלון יגאל',148,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אליהו הנביא',473,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אליכין',127,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אלישע הנביא',474,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אלנקוה רפאל',161,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אלעזרי',129,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אמרי אמת',211,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אמרי נועם',504,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אסתר',513,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ארלוזורוב',110,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אשכול לוי',242,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אשר',231,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('באר שבע',487,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בוסקילה יוסף',128,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ביאליק',123,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ביחר שמשון',109,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בית ג''מאל',130,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בית זולוטוב',149,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בית ישראל',226,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בית שמש',9000,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בית שמש הותיקה',6509,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בן איש חי',189,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בן אליעזר',202,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בן גוריון פולה',254,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בן גרא',158,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בן זאב יהודה',252,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בן עזאי',450,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בן צבי',145,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בן ציון אבא שאול',187,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בנאי יוסי',297,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בני דן',124,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בעל התניא',505,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בר אילן',203,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בר קפרא',361,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ברכת אברהם',229,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('גבעת בן צבי',6527,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('גבעת ויצמן',6526,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('גבעת סביון',6517,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('גבעת שזר',6528,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('גבעת שרת',6501,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('גד',232,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('גונן שמואל',240,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('גור אריה',122,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('גלעד',243,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('גני יהודית',6507,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('גני שמש',6502,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('דובר שלום',453,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('דורי יעקב',257,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('דליה',116,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('דם המכבים',111,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('דניאל',515,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('דרך החיים',285,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('דרך רבין יצחק',247,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('דרכי אליעזר',449,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('האגס',272,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('האדמור מבעלזא',502,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('האדמור מרוז''ין',506,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('האדרת',507,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('האומן',106,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('האורן',268,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('האיריס',166,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('האלה',125,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('האפרסק',273,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('האצל',138,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הארבל',244,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הארז',274,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הארזים',174,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('האתרוג',269,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הבנאי',141,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הבעל שם טוב',508,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הברוש',266,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הגאון מוילנא',509,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הגולן',251,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הגליל',248,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הגפן',115,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הדובדבן',176,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הדולב',278,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ההדס',270,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ההדר',263,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ההכשרה',305,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הושע הנביא',476,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הותיקים',155,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('החבצלת',193,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('החוזה מלובלין',526,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('החלוצים',104,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('החפץ חיים',188,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('החצב',191,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('החרובים',264,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('החרוצים',306,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('החרמון',245,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('החרצית',192,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('החרש',152,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('היסמין',195,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('היצירה',301,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הכלנית',167,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הלל',495,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('המגיד ממעזריטש',527,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('המהריל דיסקין',220,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('המורה יעקב',136,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('המכתש',126,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('המלאכה',304,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('המלך דוד',511,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('המסגר',142,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('המעפילים',121,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('המשלט',112,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הנורית',165,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הנציב',528,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הנרקיס',169,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הנשיא',113,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הסביון',168,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הסוללה',308,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הסיגלית',163,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רועי קליין',373,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('העליה',105,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('העמל',303,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הערבה',265,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הערמון',275,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הצאלה',276,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הצבע',310,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הצדיק משטפנשט',448,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הציפורן',194,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הר בשן',286,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הר גבנונים',289,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הר הכרמל',300,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הר המוריה',287,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הר מירון',288,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הר נבו',284,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב אלישיב',534,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב גריינימן',532,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב האדמור החלוץ',531,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב הרצוג',216,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב יוסף עזרן',533,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב יעקב יוסף',535,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב יצחק כדורי',536,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב מבריסק',213,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב מנחם פרוש',537,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב מרדכי צמח אליהו',538,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב קוק',539,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב שלמה זלמן',546,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב שלמה לורניץ',540,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרטוב',279,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרצל',101,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרקפת',164,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרשר הירש',547,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('השבעה',144,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('השושן',190,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('השיזף',277,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('השיטה',261,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('השקד',131,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('התאנה',262,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('התבור',246,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('התעשיה',302,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('התפוח',271,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('וירג''יניה',307,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ורד',207,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ז''בוטינסקי',103,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('זכרון יעקב',209,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('זכריה הנביא',480,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('חבקוק הנביא',481,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('חברון',485,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('חגי הנביא',426,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('חזון איש',212,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('חידא',186,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('חלקת יהושע',541,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('חצרות ערבי הנחל',444,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אלבז',380,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('טבריה',488,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('יאיר',378,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('יבנה',489,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ידין יגאל',255,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('יהודה הלוי',294,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('יהודה המכבי',180,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('יואל הנביא',484,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('יוכבד',542,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('יונה בן אמיתי',427,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('יונתן בן עוזיאל',183,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('יחזקאל הנביא',523,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('יצחק שדה',204,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ירושלים',490,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ירמיהו הנביא',524,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ישעיהו הנביא',521,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('כביש 38',185,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ככר נוימן',6001,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('השלושה',377,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('לב שמחה',221,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('לוין אריה',239,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('לנר דן',235,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('לסקוב חיים',241,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מגן קלמן',236,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מורדי הגטאות',153,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מורי יעקב',157,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מחזיקי הדת',501,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מיטל',282,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מלאכי הנביא',518,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מנדלר אלברט',238,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מנוח',118,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מנור אהוד',296,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מנחת יצחק',228,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מעלה דוד',132,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מעלה הסיירים',133,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מעלה הצופים',134,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מעלה יאיר',135,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מעלות הרמא',500,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מעפילי אגוז',230,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מערבא',354,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מעשי חייא',225,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מצדה',139,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מצפה הרשפ',494,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מקלף מרדכי',256,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מר עוקבא',350,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מרים הנביאה',522,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מרכז קליטה',151,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('משה רבנו',520,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('משטרת הרטוב',108,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('משעול המתמיד',259,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נהר הירדן',410,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נהר הירקון',420,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נהרדעא',351,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נוה ספיר',6519,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נועם אלימלך',544,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נופי אביב',6523,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נופי הדר',178,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחום הנביא',428,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל אוריה',411,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל איילון',412,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל אכזיב',441,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל אל-על',409,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל אלכסנדר',408,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל גילה',413,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל דולב',400,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל הבשור',439,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל הקישון',419,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל זוהר',433,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל זויתן',430,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל חבר',434,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל יעלה',401,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל לוז',414,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל לכיש',415,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל מאור',402,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל מטע',403,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל מיכה',416,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל משמר',442,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל נועם',418,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל נחשון',417,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל ניצנים',443,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל סנסן',445,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל עין גדי',435,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל ערוגות',436,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל קטלב',404,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל רביבים',440,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל רזיאל',405,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל רמות',421,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל רפאים',438,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל שורק',422,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל שחם',423,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל שמשון',406,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל שניר',429,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל תמנע',407,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל תמר',424,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחמיה',516,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('חגואל',384,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נעמי שמר',295,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נפתלי',253,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נריה הנביא',447,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נתיב מאיר',196,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('סולם יעקב',210,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('סורא',360,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('סחלב',208,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('טרומפלדור',372,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('סיני',137,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('סיתוונית',206,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('סמ בן אליעזר',199,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('סמ האלון',181,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('סמ הגפן',154,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('סמ ויצו',143,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('סמ עלית הנוער',249,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('סמדר',117,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('פרנקל',375,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('עזרא',517,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('עידו הנביא',519,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('עלית הנוער',250,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('עמק הזיתים',114,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('עקביא בן מהללאל',452,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('פומפדיתא',355,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('פסגות השבע',6522,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('פעמי משיח',497,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('פרס ראובן',177,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('צפת',491,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('צריפים אדומים',6504,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('קארו יוסף',197,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('קדושת אהרון',457,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('קהילת יעקב',218,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('קריית ארבע',486,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('קרית אריה',6518,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('קרית בן אליעזר',6521,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('קרית החינוך',6532,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('קרית הרב ניסים',6520,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('קרית הרמא',6530,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('קרן היסוד',147,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ראובן',234,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב אבדימי',357,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב אבהו',332,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב אמי',338,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב אמימר',342,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב אשי',339,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב המנונא',349,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב זביד',337,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב זירא',343,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב חנן',345,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב כהנא',353,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב מנשיא',348,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב מרי',359,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב עולא',341,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב עמרם',358,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב פפא',336,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב שילא',346,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב ששת',331,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב תנחומא',335,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבא',344,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי אלעזר',465,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי טרפון',468,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי יהודה הנשיא',463,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי יהושע',462,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי יוסי בן קיסמא',451,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי ינאי',458,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי ישמעאל',456,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי לויטס',464,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי מאיר בעל הנס',467,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי עקיבא',460,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי פנחס בן יאיר',454,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי צדוק',469,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי צדקה יהודה',198,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבינא',334,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רביצקי',159,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבן יוחנן בן זכאי',471,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבנו חיים הלוי',217,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רויטל',283,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רות',514,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רזיאל דוד',258,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רחל המשוררת',298,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ריבל',470,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רימון',182,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ריש לקיש',347,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רמבם',140,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רמת בית שמש',6525,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רמת בית שמש ב',6531,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רמת לחי',120,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רשי',205,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רשבג',461,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רשבי',466,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ש 160',6513,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ש 144',6514,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ש 116',6515,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ש ותיקים',6505,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ש חצרות',6506,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ש משק עזר',6508,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ש קוטג''',6512,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ש רמת לחי',6510,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שאול המלך',512,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('משה ארנס',381,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב ספקטור',214,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שביל האשל',171,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שביל הגיחון',437,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שביל הלה',102,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שביל הנחש',446,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שביל התמרים',156,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שד בן גוריון',200,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שד הדקל',162,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שד נהר הדן',201,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שד נחל צאלים',492,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שד'' האמוראים',333,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שועלי שמשון',119,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שכ הגפן',6503,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שכ השחר',6529,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שכ מחסיה',6524,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שכ קרית חזון עובדיה',6534,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שכ רמת התנאים',6533,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שלמה המלך',510,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שמואל הנביא',493,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שמעון',233,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שער השמיים',227,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שפת אמת',219,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שקמה',172,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('תאשור',267,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('תדהר',175,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('תחנת הרכבת',107,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('תכלת מרדכי',459,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('תלמוד בבלי',352,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('תלמוד ירושלמי',356,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('פרנק',374,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('תמר',545,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('תפארת משה',160,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('חביבה רייך',382,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אודם',318,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('אילפא',570,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בזלת',319,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בנימין',323,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('בעל הסולם',325,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('גרניט',316,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('דבורה הנביאה',550,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('דלומיט',315,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('דרכי איש',552,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('המורה צבי',260,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הנביא עובדיה',311,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הנביא עמוס',312,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הנביא צפניה',529,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב אברהם שפירא',551,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב איידלשטיין',553,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב ברוק',556,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב ישראל גרוסמן',554,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('הרב ליפקוביץ',555,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('זעירי',568,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('חולדה הנביאה',314,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('חושן',309,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('טופז',321,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('טורקיז',299,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('יהלום',317,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מר זוטרא',560,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('מר ינוקא',564,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל פולג',530,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל פרת',548,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נחל קדרון',543,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('נתן הנביא',313,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('סלע',322,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('ספיר',320,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('קריסטל',324,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב חלקיה בר טובי',563,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב חננאל',565,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב חסדא',561,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב ייבא סבא',569,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רב משרשיא',567,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי ברכיה',557,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי חזקיה',562,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי חלבו',571,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי חנינא',558,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי יצחק נפחא',559,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('רבי פרדא',566,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('שד נחל נובע',549,2610);
INSERT INTO Streets (StreetName, StreetID, CityId) VALUES ('תפארת נפתלי',525,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (547,6,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (546,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (545,9,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (544,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (544,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (542,9,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (541,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (540,26,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (539,6,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (539,6,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (538,6,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (538,6,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (537,26,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (537,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (536,6,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (536,6,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (535,6,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (534,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (534,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (533,26,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (532,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (532,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (531,6,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (528,6,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (528,6,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (528,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (527,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (526,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (524,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (523,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (522,9,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (521,26,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (521,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (521,26,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (521,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (521,26,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (521,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (521,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (520,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (519,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (518,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (517,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (516,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (515,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (514,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (513,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (512,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (511,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (510,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (509,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (508,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (507,6,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (506,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (505,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (504,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (503,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (501,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (495,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (494,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (493,9,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (493,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (492,18,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (492,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (491,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (490,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (489,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (488,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (487,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (486,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (485,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (484,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (481,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (480,18,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (476,9,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (474,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (473,18,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (473,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (473,17,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (473,9,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (473,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (473,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (471,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (470,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (469,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (468,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (467,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (466,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (465,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (464,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (463,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (462,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (461,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (460,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (459,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (458,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (456,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (456,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (455,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (455,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (454,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (453,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (453,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (452,10,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (451,10,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (451,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (450,10,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (448,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (447,18,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (447,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (445,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (443,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (442,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (441,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (439,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (438,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (437,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (436,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (435,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (434,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (433,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (432,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (432,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (430,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (429,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (428,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (427,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (426,18,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (426,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (425,15,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (424,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (423,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (422,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (421,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (420,11,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (420,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (420,6,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (420,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (419,26,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (419,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (419,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (418,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (417,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (416,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (415,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (414,27,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (414,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (413,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (412,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (411,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (410,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (410,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (410,24,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (409,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (407,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (406,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (405,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (404,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (403,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (402,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (401,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (400,23,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (314,9,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (313,9,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (312,9,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (311,17,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (311,9,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (310,3,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (307,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (304,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (303,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (302,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (302,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (302,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (302,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (302,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (301,1,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (298,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (297,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (296,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (295,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (294,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (293,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (289,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (288,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (287,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (286,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (286,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (285,13,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (284,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (284,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (284,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (284,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (283,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (282,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (281,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (280,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (279,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (278,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (277,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (276,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (275,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (275,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (274,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (273,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (272,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (271,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (270,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (269,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (268,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (267,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (265,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (264,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (263,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (262,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (261,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (260,3,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (258,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (257,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (256,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (255,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (254,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (254,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (253,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (252,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (252,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (252,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (252,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (252,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (251,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (250,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (247,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (246,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (246,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (245,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (245,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (244,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (244,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (243,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (243,13,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (243,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (242,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (242,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (242,13,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (242,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (241,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (240,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (239,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (238,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (237,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (236,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (235,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (234,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (234,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (233,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (232,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (231,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (230,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (230,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (229,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (228,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (227,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (226,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (225,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (224,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (223,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (222,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (221,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (220,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (219,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (218,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (218,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (217,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (216,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (216,10,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (216,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (215,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (214,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (213,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (212,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (212,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (211,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (210,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (209,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (208,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (207,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (205,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (205,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (205,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (205,8,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (205,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (204,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (203,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (202,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (202,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (200,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (198,13,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (197,13,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (195,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (194,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (193,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (192,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (191,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (190,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (189,13,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (188,13,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (187,13,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (186,13,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (182,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (181,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (180,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (177,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (176,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (175,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (174,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (172,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (171,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (169,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (168,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (167,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (166,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (165,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (164,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (164,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (163,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (162,14,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (162,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (162,7,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (161,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (160,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (159,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (158,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (157,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (157,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (156,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (155,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (154,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (153,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (152,3,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (148,3,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (147,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (145,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (144,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (143,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (142,3,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (141,3,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (140,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (139,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (139,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (138,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (137,12,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (135,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (134,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (132,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (131,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (129,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (127,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (126,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (125,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (124,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (123,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (122,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (121,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (119,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (118,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (117,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (116,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (115,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (114,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (113,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (113,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (112,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (112,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (111,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (110,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (106,3,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (105,3,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (105,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (104,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (103,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (102,25,2610);
INSERT INTO StreetToNeighborhood (StreetId, NeighborhoodId, CityId) VALUES (101,25,2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('א.ת ברוש,בית שמש מערב',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('א.ת הר-טוב',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('א.ת צפוני',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('א.ת שורק-נוחם',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('א.ת שורק-נוחם',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('גבעת משקפיים',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('גבעת שרת',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('הקריה החרדית',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('חזון עובדיה,רמת בית שמש ג--2',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('ממזרח שמש',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('נווה שמיר ,רמת בית שמש ה-1',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('פסגות השבע',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('קנה בושם,חפציבה',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('קרית אריה,שיינפלד',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('רמת אבי עזרי,רמת בית שמש ג-1',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('רמת אברהם',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('רמת בית שמש ה-2',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('רמת האמוראים,רמת בית שמש ד-1',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('רמת האמוראים,רמת בית שמש ד-2',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('רמת האמוראים,רמת בית שמש ד-3',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('רמת האמוראים,רמת בית שמש ד-4',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('רמת האמוראים,רמת בית שמש ד-5',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('רמת הנחלים,רמת בית שמש א',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('רמת התנאים,רמת בית שמש ב',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('רמת משה,בית שמש הוותיקה',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('שכונת המע""ר',2610);
INSERT INTO Neighborhoods (NeighborhoodName, CityId) VALUES ('שכונת מ-3',2610);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
